# Generated by Django 6.0.4 on 2026-04-21 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="ID Unique d'Installation")),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Installation")),
                ('last_sync_portal', models.DateTimeField(blank=True, null=True, verbose_name='Dernière Synchro Portail')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nom de la Société')),
                ('company_address', models.TextField(verbose_name='Adresse du Siège')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contact')),
                ('company_website', models.URLField(blank=True, verbose_name='Site Web')),
                ('company_vat', models.CharField(blank=True, max_length=50, verbose_name='Numéro de TVA')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='system/logos/', verbose_name='Logo Entreprise')),
            ],
            options={
                'verbose_name': 'Configuration Système',
                'verbose_name_plural': 'Configuration Système',
            },
        ),
    ]
