# Generated by Django 6.0.4 on 2026-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Site Web'),
        ),
    ]
