# Generated by Django 6.0.4 on 2026-10-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_systemconfiguration_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='installation_secret',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name="Secret d'installation"),
        ),
    ]
