"""
Django settings for smartops_project project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os
import sqlite3
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def get_dynamic_apps():
    """
    Récupère la liste des applications premium activées directement en SQL 
    pour éviter de charger l'ORM Django trop tôt (problème de l'œuf et la poule).
    """
    dynamic_apps = []
    db_path = BASE_DIR / 'db.sqlite3'
    
    if os.path.exists(db_path):
        try:
            conn = sqlite3.connect(db_path)
            cursor = conn.cursor()
            # On récupère le chemin python des modules actifs, triés par priorité
            cursor.execute("SELECT python_path FROM licensing_plugin WHERE is_active=1 ORDER BY priority ASC")
            dynamic_apps = [row[0] for row in cursor.fetchall() if row[0]]
            conn.close()
        except Exception:
            # En cas d'erreur (ex: table non encore créée au premier migrate), on ignore
            pass
    return dynamic_apps

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a43ml7%bpwm2&*18ay)jt24gam!89wh0oss150hxc)$8&0(+uc'

DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # SMARTOPS Core Applications
    'accounts.apps.AccountsConfig',
    'system.apps.SystemConfig',
    'licensing.apps.LicensingConfig',
    'inventory.apps.InventoryConfig',
]

# Injection automatique des plugins depuis la base de données
INSTALLED_APPS += get_dynamic_apps()

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartops_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'system.context_processors.system_settings',
                'plugins_system.context_processors.plugin_menus',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartops_project.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Security: Isolate cookies
SESSION_COOKIE_NAME = 'smartops_sessionid'
CSRF_COOKIE_NAME = 'smartops_csrftoken'

# Auth redirects
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'accounts.CustomUser'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
