"""
Django settings for smartops_project project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os
import sqlite3
from pathlib import Path
import environ
import pymysql

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Support MySQL via PyMySQL
pymysql.version_info = (2, 2, 8, "final", 0)
pymysql.install_as_MySQLdb()

# Initialisation de django-environ
env = environ.Env(
    DEBUG=(bool, False)
)
# Lecture du fichier .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

def get_dynamic_apps():
    """
    Récupère la liste des applications premium activées directement en SQL 
    pour éviter de charger l'ORM Django trop tôt (problème de l'œuf et la poule).
    Supporte SQLite et MySQL.
    """
    dynamic_apps = []
    # On récupère la config comme Django le ferait (par défaut sqlite)
    db_url = env('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
    db_config = env.db_url_config(db_url)
    
    try:
        if 'mysql' in db_config['ENGINE']:
            conn = pymysql.connect(
                host=db_config.get('HOST', 'localhost'),
                user=db_config.get('USER'),
                password=db_config.get('PASSWORD'),
                database=db_config.get('NAME'),
                port=int(db_config.get('PORT', 3306))
            )
            cursor = conn.cursor()
            cursor.execute("SELECT python_path FROM licensing_plugin WHERE is_active=1 ORDER BY priority ASC")
            dynamic_apps = [row[0] for row in cursor.fetchall() if row[0]]
            conn.close()
        elif 'sqlite3' in db_config['ENGINE']:
            db_path = db_config['NAME']
            if os.path.exists(db_path):
                conn = sqlite3.connect(db_path)
                cursor = conn.cursor()
                cursor.execute("SELECT python_path FROM licensing_plugin WHERE is_active=1 ORDER BY priority ASC")
                dynamic_apps = [row[0] for row in cursor.fetchall() if row[0]]
                conn.close()
    except Exception:
        # En cas d'erreur (ex: table non encore créée au premier migrate), on ignore
        pass
    return dynamic_apps

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-a43ml7%bpwm2&*18ay)jt24gam!89wh0oss150hxc)$8&0(+uc')

DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # SMARTOPS Core Applications
    'accounts.apps.AccountsConfig',
    'system.apps.SystemConfig',
    'licensing.apps.LicensingConfig',
    'inventory.apps.InventoryConfig',
    'maintenance.apps.MaintenanceConfig',
    'schedule',
]

# Injection automatique des plugins depuis la base de données
INSTALLED_APPS += get_dynamic_apps()

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartops_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'system.context_processors.system_settings',
                'plugins_system.context_processors.plugin_menus',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartops_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases
DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Security: Isolate cookies
SESSION_COOKIE_NAME = 'smartops_sessionid'
CSRF_COOKIE_NAME = 'smartops_csrftoken'

# Auth redirects
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'accounts.CustomUser'
# Default Auto Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURATION INTERCONNEXION (PFE) ---
# MARKETPLACE_URL : URL du portail commercial SMARTOPS_PORTAL.
# En local (DEBUG=True), on pointe vers le port par défaut de Django (8000).
# En production, on utilise le domaine sécurisé.
MARKETPLACE_URL = env('MARKETPLACE_URL', default='https://www.opensmartops.org' if not DEBUG else 'http://127.0.0.1:8000')

