# Generated by Django 6.0.4 on 2026-08-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('technician', 'Technicien')], default='technician', max_length=20, verbose_name='Rôle'),
        ),
    ]
