# Generated by Django 6.0.4 on 2026-04-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifiant technique unique du plugin (ex: smartops-billing)', unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du Plugin')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version Installée')),
                ('license_key_hash', models.CharField(blank=True, help_text='Hachage de la clé de licence pour vérification locale', max_length=255)),
                ('is_active', models.BooleanField(default=False, verbose_name="Statut d'Activation")),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Installation")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière Mise à Jour')),
            ],
            options={
                'verbose_name': 'Module Premium',
                'verbose_name_plural': 'Modules Premium',
            },
        ),
    ]
