# Generated by Django 6.0.4 on 2026-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='priority',
            field=models.IntegerField(default=100, help_text='Ordre de chargement dans INSTALLED_APPS (le plus petit en premier)'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='python_path',
            field=models.CharField(blank=True, help_text="Le chemin d'importation Python (ex: smartops_plugin_demo)", max_length=255),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='slug',
            field=models.SlugField(help_text='Identifiant technique unique (ex: smartops-billing)', unique=True),
        ),
    ]
