# Generated by Django 6.0.4 on 2026-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_plugin_priority_plugin_python_path_alter_plugin_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='license_key_hash',
        ),
        migrations.AddField(
            model_name='plugin',
            name='license_key',
            field=models.CharField(blank=True, help_text='Clé de licence (UUID) utilisée pour ce module', max_length=255),
        ),
    ]
