# Generated by Django 6.0.4 on 2026-04-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du Client')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du Bâtiment')),
                ('address', models.TextField(verbose_name='Adresse du Bâtiment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='inventory.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'équipement")),
                ('equipment_type', models.CharField(choices=[('hvac', 'Chauffage, Ventilation, Climatisation'), ('security', 'Sécurité'), ('medical', 'Médical'), ('industrial', 'Industriel'), ('elevator', 'Ascenseur'), ('it', 'Informatique')], max_length=50, verbose_name="Type d'équipement")),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('installed_at', models.DateField(verbose_name="Date d'installation")),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='inventory.building', verbose_name='Bâtiment')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
    ]
