# Generated by Django 6.0.4 on 2026-04-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de TVA'),
        ),
    ]
