# Generated by Django 6.0.4 on 2026-04-28 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_client_phone_client_vat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du type')),
            ],
            options={
                'verbose_name': "Type d'équipement",
                'verbose_name_plural': "Types d'équipement",
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Champs personnalisés'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.equipmenttype', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='EquipmentTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Nom du champ')),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('date', 'Date')], max_length=20, verbose_name='Type de champ')),
                ('required', models.BooleanField(default=False, verbose_name='Requis')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inventory.equipmenttype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Champ personnalisé',
                'verbose_name_plural': 'Champs personnalisés',
            },
        ),
    ]
