# Generated by Django 6.0.4 on 2026-09-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipmenttype_equipment_custom_fields_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Lieu', 'verbose_name_plural': 'Lieux'},
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(verbose_name='Adresse du lieu'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du lieu'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='inventory.building', verbose_name='Lieu'),
        ),
    ]
