# Generated by Django 6.0.4 on 2026-06-05 11:07
# Fixed: replaced RenameIndex(old_fields=...) with SeparateDatabaseAndState + AddIndex
# because Django 6.0 makes AlterIndexTogether a DB no-op, so there are no unnamed
# indexes to rename. We clear the index_together state and create named indexes directly.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        # Clear the old index_together state without touching the DB
        # (in Django 6.0, AlterIndexTogether is already a DB no-op, so the unnamed
        # indexes may or may not exist — we handle both cases below)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterIndexTogether(
                    name='calendarrelation',
                    index_together=set(),
                ),
                migrations.AlterIndexTogether(
                    name='event',
                    index_together=set(),
                ),
                migrations.AlterIndexTogether(
                    name='eventrelation',
                    index_together=set(),
                ),
                migrations.AlterIndexTogether(
                    name='occurrence',
                    index_together=set(),
                ),
            ],
            database_operations=[],
        ),
        # Create named indexes (CREATE INDEX IF NOT EXISTS handles both fresh DBs
        # and existing DBs where the unnamed index was already present)
        migrations.AddIndex(
            model_name='calendarrelation',
            index=models.Index(fields=['content_type', 'object_id'], name='schedule_ca_content_cddadb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start', 'end'], name='schedule_ev_start_a258cb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrelation',
            index=models.Index(fields=['content_type', 'object_id'], name='schedule_ev_content_6ceecb_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['start', 'end'], name='schedule_oc_start_76a2f8_idx'),
        ),
    ]
