# Generated by Django 6.0.4 on 2026-04-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_equipmenttype_equipment_custom_fields_and_more'),
        ('schedule', '0015_rename_calendarrelation_content_type_object_id_schedule_ca_content_cddadb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='Liste des compétences (ex: Electrique, Hydraulique)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maintenance', 'Maintenance Préventive'), ('repair', 'Dépannage / Réparation'), ('emergency', 'Urgence')], default='maintenance', max_length=50)),
                ('planned_start', models.DateTimeField(verbose_name='Début prévu')),
                ('planned_end', models.DateTimeField(verbose_name='Fin prévue')),
                ('effective_start', models.DateTimeField(blank=True, null=True, verbose_name='Début réel')),
                ('effective_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin réelle')),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('planned', 'Planifié'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('canceled', 'Annulé')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description du problème / travail')),
                ('intervention_report', models.TextField(blank=True, verbose_name="Rapport d'intervention")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='inventory.equipment')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_ticket', to='schedule.event')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='maintenance.technician')),
            ],
            options={
                'verbose_name': 'Ticket de Maintenance',
                'verbose_name_plural': 'Tickets de Maintenance',
            },
        ),
    ]
