# Generated by Django 6.0.4 on 2026-08-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipmenttype_equipment_custom_fields_and_more'),
        ('maintenance', '0001_initial'),
        ('schedule', '0015_rename_calendarrelation_content_type_object_id_schedule_ca_content_cddadb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='inventory.equipment', verbose_name='Équipement'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_ticket', to='schedule.event', verbose_name='Événement calendrier'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de début'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de début'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('planned', 'Planifié'), ('in_progress', 'En cours'), ('to_reschedule', 'À replanifier'), ('done', 'Terminé'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='maintenance.technician', verbose_name='Technicien'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='type',
            field=models.CharField(choices=[('maintenance', 'Maintenance Préventive'), ('repair', 'Dépannage / Réparation'), ('emergency', 'Urgence')], default='maintenance', max_length=50, verbose_name="Type d'intervention"),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='Liste des compétences (ex: Electrique, Hydraulique)', verbose_name='Spécialités'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceticket',
            constraint=models.CheckConstraint(condition=models.Q(('planned_end__gt', models.F('planned_start'))), name='ticket_planned_end_after_planned_start'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceticket',
            constraint=models.CheckConstraint(condition=models.Q(('effective_start__isnull', True), ('effective_end__isnull', True), ('effective_end__gt', models.F('effective_start')), _connector='OR'), name='ticket_effective_end_after_effective_start'),
        ),
    ]
