# Generated by Django 6.0.4 on 2026-06-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('planned', 'Planifié'), ('in_progress', 'En cours'), ('to_reschedule', 'À replanifier'), ('done', 'Terminé'), ('canceled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
