# Generated by Django 6.0.4 on 2026-09-10 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenanceticket_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interventions/%Y/%m/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('phase', models.CharField(choices=[('before', 'Avant intervention'), ('during', 'Pendant intervention'), ('after', 'Après intervention')], default='during', max_length=20, verbose_name='Moment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.maintenanceticket', verbose_name='Intervention')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_photos', to=settings.AUTH_USER_MODEL, verbose_name='Ajoutée par')),
            ],
            options={
                'verbose_name': "Photo d'intervention",
                'verbose_name_plural': "Photos d'intervention",
                'ordering': ['uploaded_at'],
            },
        ),
    ]
