name: Django CI

on:
  push:
    branches: [ "main", "feat-*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Patch Scheduler Library
      run: |
        # On corrige l'index bug directement dans le site-packages de la CI
        sed -i 's/models.Index(fields=\["content_type", "object_id"\]),/models.Index(fields=\["content_type_id", "object_id"\]),/' $(python -c "import site; print(site.getsitepackages()[0])")/schedule/models/calendars.py
    - name: Run Tests
      run: |
        python manage.py test
      env:
        SECRET_KEY: "ci-test-key-not-for-production"
        DEBUG: "True"
